name: Auto Generate README Gallery

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run PowerShell script
        shell: pwsh
        run: |
          ./up.ps1

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add README.md
          git diff --cached --quiet || git commit -m "Auto update README gallery"
          git push
